site_name: ArgoCD
nav:
  - ArgoCD: index.md
  - ArgoCD Install: argocd.md
theme:
  name: material
  nav_style: dark
  palette:
    scheme: slate
    primary: indigo
    accent: light blue
plugins:
  - search